{
 "title": "k6 + RGW perf",
 "description": "Visualize k6 OSS results stored in Prometheus with Native Histograms.",
 "time": { "from": "2025-09-19T08:32:45.000Z", "to": "2025-09-19T09:25:00.000Z" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus DS", "query": "prometheus" },
   { "name": "testid", "label": "Test ID", "query": { "query": "label_values(testid)" } },
   { "name": "quantile", "label": "Trend Metrics Query", "query": "0.90" },
   { "name": "adhoc_filter", "label": "AdhocFilter" }
  ]
 },
 "panels": [
  {
   "title": "Performance Overview",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum by (le) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_avg(sum by (le) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
     "legendFormat": "avg"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "http_req_s"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_errors"
    }
   ]
  },
  {
   "title": "Latency / IOPS",
   "type": "xychart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "(sum by() (rate(k6_http_reqs_total[$__rate_interval]))\n   AND\n   stddev_over_time(sum(rate(k6_http_reqs_total[$__rate_interval]))[1m:]) < 50)",
     "legendFormat": "iops"
    },
    {
     "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
     "legendFormat": "p$quantile"
    }
   ]
  },
  {
   "title": "RGW Latency / IOPS",
   "type": "xychart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "(sum by() (rate(rgw_ops_status_total{status=\"0\"}[$__rate_interval]))\n   AND\n   stddev_over_time(sum(rate(rgw_ops_status_total{status=\"0\"}[$__rate_interval]))[1m:]) < 50)",
     "legendFormat": "iops"
    },
    {
     "expr": "histogram_quantile($quantile, sum by(le, job) (rate(rgw_ops_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p$quantile"
    }
   ]
  },
  {
   "title": "K6 HTTP Req Duration",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(le) (rate(k6_http_req_duration_seconds[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Latency Stats",
   "type": "timeseries",
   "description": "Select a different quantile to change the query",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) ((rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval]))))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(.90, sum by (le) ((rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval]))))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(.95, sum by (le) ((rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval]))))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(.99, sum by (le) ((rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval]))))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0, sum by (le) ((rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval]))))",
     "legendFormat": "min"
    },
    {
     "expr": "histogram_avg(sum by (le) ((rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval]))))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "RGW Beast Latency",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by (le) (rate(rgw_beast_latency_seconds_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RGW Op Latency (mtail rgw_op_latency)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(rgw_ops_latency_seconds_bucket[$__rate_interval])))\n",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, job) (rate(rgw_ops_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, job) (rate(rgw_ops_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "med"
    },
    {
     "expr": "sum by (job) (rate(rgw_ops_latency_seconds_sum[30s]))\n/ \nsum by (job) (rate(rgw_ops_latency_seconds_count[30s]))",
     "legendFormat": "avg"
    }
   ]
  },
  { "title": "Performance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "http_req_s"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_errors"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"true\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_success"
    }
   ]
  },
  {
   "title": "HTTP Latency Timings",
   "type": "timeseries",
   "description": "Select a different quantile to change the query\n\n<a href=\"https://k6.io/docs/using-k6/metrics/reference/#http\" target=\"_blank\">HTTP-specific built-in metrics</a>",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_http_req_blocked_seconds{testid=~\"$testid\"}[$__rate_interval])))",
     "legendFormat": "http_req_blocked_q$quantile"
    },
    {
     "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_http_req_tls_handshaking_seconds{testid=~\"$testid\"}[$__rate_interval])))",
     "legendFormat": "http_req_tls_handshaking_q$quantile"
    },
    {
     "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_http_req_sending_seconds{testid=~\"$testid\"}[$__rate_interval])))",
     "legendFormat": "http_req_sending_q$quantile"
    },
    {
     "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_http_req_waiting_seconds{testid=~\"$testid\"}[$__rate_interval])))",
     "legendFormat": "http_req_waiting_q$quantile"
    },
    {
     "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_http_req_receiving_seconds{testid=~\"$testid\"}[$__rate_interval])))",
     "legendFormat": "http_req_receiving_q$quantile"
    },
    {
     "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
     "legendFormat": "http_req_duration_q$quantile"
    }
   ]
  },
  {
   "title": "HTTP Status Rate (mtail rgw_ops_status_total)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (http_status) (rate(rgw_ops_status_total{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by URL",
   "type": "table",
   "description": "min/max/p95/p99 depends on the available Quantile Stats",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "histogram_quantile(0, sum by(le, name, method, status) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
     "legendFormat": "min"
    },
    {
     "expr": "histogram_quantile(1, sum by(le, name, method, status) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, name, method, status) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, name, method, status) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checks Success Rate (aggregate individual checks)",
   "type": "timeseries",
   "description": "Filter by check name to query a particular check",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "avg(round(k6_checks_rate{testid=~\"$testid\"}, 0.1)*100)",
     "legendFormat": "k6_checks_rate"
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(irate(k6_data_sent_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "data_sent"
    },
    {
     "expr": "avg(irate(k6_data_received_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "data_received"
    }
   ]
  }
 ]
}