{
 "title": "rgw perf",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "RGW Perf", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "New panel",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_rgw_qlen", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "RGW Req In Flight",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "targets": [
    { "expr": "ceph_rgw_qlen", "legendFormat": "{{pod}} ({{instance}})" }
   ]
  },
  {
   "title": "Latency Histogram All Requests",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (le) (rate(rgw_beast_latency_seconds_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RGW Op Latency (mtail rgw_op_latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(rgw_ops_latency_seconds_bucket[$__rate_interval])))\n",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, job) (rate(rgw_ops_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, job) (rate(rgw_ops_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "med"
    },
    {
     "expr": "sum by (job) (rate(rgw_ops_latency_seconds_sum[$__rate_interval]))\n/ \nsum by (job) (rate(rgw_ops_latency_seconds_count[$__rate_interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Req Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(ceph_rgw_req[$__rate_interval]))",
     "legendFormat": "reqs"
    },
    {
     "expr": "sum(rate(ceph_rgw_failed_req[$__rate_interval]))",
     "legendFormat": "fail"
    }
   ]
  },
  {
   "title": "RGW GET Op Latency (mtail rgw_op_latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(job, le) (rate(rgw_beast_latency_seconds_bucket{verb=\"GET\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, job) (rate(rgw_beast_latency_seconds_bucket{verb=\"GET\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, job) (rate(rgw_beast_latency_seconds_bucket{verb=\"GET\"}[$__rate_interval])))",
     "legendFormat": "med"
    },
    {
     "expr": "sum by (job) (rate(rgw_beast_latency_seconds_sum{verb=\"GET\"}[$__rate_interval]))\n/ \nsum by (job) (rate(rgw_beast_latency_seconds_count{verb=\"GET\"}[$__rate_interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Req Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(ceph_rgw_req[$__rate_interval])",
     "legendFormat": "reqs {{instance}}"
    },
    {
     "expr": "rate(ceph_rgw_failed_req[$__rate_interval])",
     "legendFormat": "fail {{instance}}"
    }
   ]
  },
  {
   "title": "RGW PUT Op Latency (mtail rgw_op_latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(job, le) (rate(rgw_beast_latency_seconds_bucket{verb=\"PUT\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, job) (rate(rgw_beast_latency_seconds_bucket{verb=\"PUT\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, job) (rate(rgw_beast_latency_seconds_bucket{verb=\"PUT\"}[$__rate_interval])))",
     "legendFormat": "med"
    },
    {
     "expr": "sum by(job) (rate(rgw_beast_latency_seconds_sum{verb=\"PUT\"}[$__rate_interval])) / (sum by(job) (rate(rgw_beast_latency_seconds_count{verb=\"PUT\"}[$__rate_interval])))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "RGW Simple Throttle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(ceph_simple_throttler_outstanding[$__rate_interval]))",
     "legendFormat": "outstanding"
    },
    {
     "expr": "sum(rate(ceph_simple_throttler_throttle[$__rate_interval]))",
     "legendFormat": "throttle"
    }
   ]
  },
  {
   "title": "HTTP Status Rate (mtail rgw_ops_status_total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (http_status) (rate(rgw_ops_status_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Verb + RGW Error (mtail rgw_ops_status_total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (status, verb) (rate(rgw_ops_status_total{status!=\"0\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Client Addrs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (addr) (rate(rgw_beast_addr_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP User Agents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (user_agent) (rate(rgw_beast_user_agents_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "KMS Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "KMS Fetch Op vs Total Op",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "sum(rate(ceph_rgw_kms_fetch_lat_count[5m]))",
     "legendFormat": "fetch"
    },
    {
     "expr": "sum(rate(rgw_ops_status_total[5m]))",
     "legendFormat": "total rgw ops"
    }
   ]
  },
  {
   "title": "Hit Miss Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(ceph_kms_cache_hit[5m]) / (rate(ceph_kms_cache_hit[5m]) + rate(ceph_kms_cache_miss[5m]))",
     "legendFormat": "hit / (hit+miss) {{instance}}"
    }
   ]
  },
  {
   "title": "Cache Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "sum(rate(ceph_kms_cache_hit[5m]))",
     "legendFormat": "hit"
    },
    {
     "expr": "sum(rate(ceph_kms_cache_miss[5m]))",
     "legendFormat": "miss"
    },
    {
     "expr": "sum(rate(ceph_kms_cache_expired[5m]))",
     "legendFormat": "exp"
    },
    {
     "expr": "sum(rate(ceph_kms_cache_clear[5m]))",
     "legendFormat": "clear"
    }
   ]
  },
  {
   "title": "KMS Fetch Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ceph_rgw_kms_fetch_lat_sum[5m]) / rate(ceph_rgw_kms_fetch_lat_count[5m])\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "KMS Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "sum(rate(ceph_rgw_kms_error_permanent[5m]))",
     "legendFormat": "perm"
    },
    {
     "expr": "sum(rate(ceph_rgw_kms_error_transient[5m]))",
     "legendFormat": "transient"
    },
    {
     "expr": "sum(rate(ceph_rgw_kms_error_secret_store[5m]))",
     "legendFormat": "secret store"
    }
   ]
  },
  {
   "title": "Cache Capacity vs. Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 94 },
   "targets": [
    { "expr": "min(ceph_kms_cache_capacity)", "legendFormat": "min capacity" },
    { "expr": "ceph_kms_cache_size", "legendFormat": "sz {{instance}}" }
   ]
  },
  {
   "title": "KMS Secret Store Errors (any == bad)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "ceph_rgw_kms_error_secret_store > 0",
     "legendFormat": "secret store"
    }
   ]
  }
 ]
}